apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-sriov-rdma-ds-installer
  namespace: kube-system
  labels:
    name: sriov-rdma-installer
spec:
  selector:
    matchLabels:
      name: sriov-rdma-installer
  template:
    metadata:
      labels:
        name: sriov-rdma-installer
    spec:
      hostNetwork: true
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: install-cni
          image: ccr.ccs.tencentyun.com/qiyuan/sriov-rdma-cni-installer:v0.0.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: host-cni-etc
              mountPath: /host-cni-etc
            - name: host-cni-bin
              mountPath: /host-cni-bin
      volumes:
        - name: host-cni-etc
          hostPath:
            path: /etc/cni/net.d/multus/
        - name: host-cni-bin
          hostPath:
            path: /opt/cni/bin